//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboards
{
    using System;
    using System.Collections.Generic;
    
    public partial class historySales
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int group { get; set; }
        public int quantity { get; set; }
        public decimal suma { get; set; }
        public System.DateTime week { get; set; }
    
        public virtual rootGroup rootGroup { get; set; }
    }
}
