//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboards
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopGroupWares
    {
        public shopGroupWares()
        {
            this.historySales = new HashSet<historySales>();
        }
    
        public int id { get; set; }
        public int code_group_wares { get; set; }
        public Nullable<int> code_parent_group_wares { get; set; }
        public string name { get; set; }
        public string translit { get; set; }
    
        public virtual ICollection<historySales> historySales { get; set; }
    }
}
